name: Participations

on: [push]

jobs:
  presence:
    name: presence de fichiers pour la participation
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - shell: bash
        run: |
          cd 1.Kafka
          bash .scripts/run.sh

